title: Amanda's Smash Lessons
description: A collection of lessons for understanding and improving at Super Smash Bros. Ultimate
theme: just-the-docs

url: https://tsubasamanda.github.io/smash-learning

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
